// Code generated by MockGen. DO NOT EDIT.
// Source: ./types/payload.go
//
// Generated by this command:
//
//	mockgen -source=./types/payload.go -destination=internal/mocks/payload.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
