services:
  redis:
    image: redis
    container_name: cache
    restart: always
    profiles: [minimal]
    ports:
      - '6379:6379'
  db:
    container_name: postgress
    image: postgres
    restart: always
    profiles: [minimal]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: "event-driven"
    volumes:
      - ./internal/sqlc/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "event-driven" ]
      interval: 2s
      timeout: 5s
      retries: 3
    depends_on:
      - redis
    ports:
      - "5432:5432"
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: always
    profiles: [monitoring]
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
  server:
    build:
      context: .
      target: final
    profiles: [app]
    depends_on:
      - db
      - redis
      - grafana
    ports:
      - "3333:3333"

volumes:
  grafana-storage:

